### ISSUE TITLE
Have gazelle_haskell_module discover source files

### ISSUE THREAD

**Issue by facundominguez** [tweag/gazelle_haskell_modules#10]
Currently, `gazelle_haskell_modules` requires `haskell_library/binary/test` to list all source files explicitly in the `srcs` attribute in order to find them.

This could be relaxed by providing some comment attached to the rule with a path to use for source files. Adding a new source file under the given path would have a corresponding `haskell_module` rule generated and referenced from the enclosing library/binary/test. e.g.

```python
# gazelle_haskell_modules:srcs: src/
haskell_library(
    name = "lib",
    modules = ["lib.A", "lib.B", "lib.C"],
)
```
After creating a file `src/D.hs`, the above would be updated to
```python
# gazelle_haskell_modules:srcs: src/
haskell_library(
    name = "lib",
    modules = ["lib.A", "lib.B", "lib.C", "lib.D"],
)

haskell_module(
    name = "lib.D",
    src = "src/D.hs",
    src_strip_prefix = "src/",
)
```

**Comment by googleson78** [comment]
I'll take a swing at this.
