### ISSUE TITLE
Support building project which use hs-boot files

### ISSUE THREAD

**Issue by facundominguez** [tweag/gazelle_haskell_modules#16]
Currently, `gazelle_cabal` [doesn't support hs-boot files](https://github.com/tweag/gazelle_cabal/issues/22), but once it does `himportscan` will need to recognize `SOURCE` pragmas and `gazelle_haskell_modules` will need to generate rules that depend on hs-boot files.

**Comment by googleson78** [comment]
The `gazelle_cabal` part [is done](https://github.com/tweag/gazelle_cabal/pull/29)

**Comment by googleson78** [comment]
Hey @GuillaumeGen just as a heads up, I already did the Haskell part of this a while ago in https://github.com/tweag/gazelle_haskell_modules/tree/googleson78-support-hs-boot if you want to use that as a starting point or something like that.
