### ISSUE TITLE
Parse imports using the GHC api

### ISSUE THREAD

**Issue by facundominguez** [tweag/gazelle_haskell_modules#31]
There is a call `getImports` in the ghc api which seems to return all the information that `himportscan` produces.
https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-8.10.7-release/compiler/main/HeaderInfo.hs#L56-67
```Haskell
-- | Parse the imports of a source file.
--
-- Throws a 'SourceError' if parsing fails.
getImports :: DynFlags
           -> StringBuffer -- ^ Parse this.
           -> FilePath     -- ^ Filename the buffer came from.  Used for
                           --   reporting parse error locations.
           -> FilePath     -- ^ The original source filename (used for locations
                           --   in the function result)
           -> IO (Either
               ErrorMessages
               ([(Maybe FastString, Located ModuleName)],
                [(Maybe FastString, Located ModuleName)],
                Located ModuleName))
              -- ^ The source imports, normal imports, and the module name.
```

Calling this is probably going to be preferable to maintaining our custom parser in
https://github.com/tweag/gazelle_haskell_modules/blob/4b43a2038fdc3d2b7f2aca6d80fcc680a2d11be7/himportscan/src/HImportScan/ImportScanner.hs#L132

**Comment by googleson78** [comment]
I'll investigate this.

**Comment by googleson78** [comment]
This would be much easier on newer ghcs as we wouldn't have to deal with `DynFlags`. `getImports` uses only `ParserOpts` (a much smaller subset of the "current" `DynFlags`) on ghc >=9.2.
